[package]
name = "someip-parser"
version = "0.2.0"
authors = ["ESRLabs"]
edition = "2021"

[dependencies]
bytes = "1.0"
nom = "7.1"
byteorder = "1"
ux = "0.1"
thiserror = "1.0"

[dev-dependencies]
hex = "0.4.3"
