[package]
name = "someip-parser"
version = "0.1.0"
authors = ["Jens Waechtler <jens.waechtler@esrlabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.1"
byteorder = "1"
ux = "0.1"
thiserror = "1.0"

[dev-dependencies]
hex = "0.4.3"
