[package]
name = "someip-messages"
version = "0.3.0"
authors = ["ESRLabs"]
edition = "2021"

[dependencies]
byteorder = "1"
derive_builder = "0.10.2"
thiserror = "1"

[dev-dependencies]
hex = "0.4.3"
proptest = "1"
